### ISSUE TITLE
can't cancel a request

### ISSUE THREAD

**Issue by jsntghf** [apentle/react-native-cancelable-fetch#1]
`const fetch = require('react-native-cancelable-fetch');`

`// Make fetch request`
`fetch('http://localhost/', null, 1)`
 `.then(res => res.json())`
 `.then(data => {`
    `console.log(data);`
  `});`

`// Cancel request`
`fetch.abort(1);`

works fine.

but if a request within a promise, the request can't be canceled, the code like

`const fetch = require('react-native-cancelable-fetch');`

`// Make fetch request`
`getCurrentLanguage().then(language => {`
`fetch('http://localhost/', null, 1)`
 `.then(res => res.json())`
 `.then(data => {`
    `console.log(data);`
  `});`
 `});`

`// Cancel request`
`fetch.abort(1);`

@doanndd

**Comment by doanndd** [comment]
The problem is `fetch.abort(1);` run before `fetch('http://localhost/', null, 1)`. Because `fetch('http://localhost/', null, 1)` is placed in a promise callback.
All you need to do is putting `fetch.abort(1);` in a place where run after `fetch('http://localhost/', null, 1)`. For example: you can put it on method `componentWillUnmount` of a React Component.

Thanks!

**Comment by jsntghf** [comment]
put it on method `componentDidMount`

`const fetch = require('react-native-cancelable-fetch');`

`// Make fetch request`
`getCurrentLanguage().then(language => {`
`fetch('http://localhost/', null, 1)`
`.then(res => res.json())`
`.then(data => {`
`console.log(data);`
`});`
`});`

put it on method `componentWillUnmount`

`// Cancel request`
`fetch.abort(1);`

is it ok?

@doanndd

**Comment by doanndd** [comment]
Yes, it is.
